tradingstrategy-ai/frontend

- package-lock.json
- package.json
- src/__tests__/routes/exchanges.test.ts
- src/lib/form/Form.svelte
- src/lib/form/Input.svelte
- src/lib/form/InputEmail.svelte
- src/lib/header/Navbar.svelte
- src/lib/helpers/utils.ts
- src/lib/table/Table.svelte
- src/routes/credentials.svelte
- src/routes/exchanges.svelte
- tsconfig.json
New Exchanges page on trading strategy ai.
> 1 - Add exchanges page

- src/routes/trading-view/backtesting.svelte
Close #22 
The link issue is done based on: https://stackoverflow.com/questions/69124800/sveltekit-disable-internal-link-routing-for-certain-a-links-served-from-the-s
> Fix backtesting page

- svelte.config.js
Close #36 
Based on https://github.com/sveltejs/kit/issues/3159
> Disable registering service worker

- docs/tests.md
- src/lib/content/PairListExportPage.svelte
- src/routes/index.svelte
- src/routes/trading-view/[chain]/[exchange]/export-data.svelte
- src/routes/trading-view/[chain]/[exchange_id].svelte
- tests/cypress/integration/exchangePairExport.spec.js
Users /pairs endpoint to output top 3000 pairs as Microsoft Excel.
> Add Export to Excel page

- src/lib/content/TokeninfoTable.svelte
- src/lib/explorer/TokenIndexExplorer.svelte
- src/routes/trading-view/[chain]/tokens/index.svelte
> Add new fields in tokens

- src/routes/trading-view/[chain]/[exchange]/[pair]/index.svelte
- only request candle/liquidity data client-side
- closes #82
> prevent SSR fetch errors

- src/lib/chain/tokenstandard.ts
- src/lib/content/PairInfoTable.svelte
- src/lib/content/TokeninfoTable.svelte
- src/lib/helpers/formatters.ts
- src/routes/trading-view/[chain]/[exchange]/[pair]/index.svelte
- src/routes/trading-view/[chain]/tokens/[token]/index.svelte
- QA fixes for the token page to make it ready for the public
- Link from the trading pair page
- Remove direct token addresses on a trading pair page
> Token page improvements

- src/lib/chart/ChartIQ.svelte
- src/lib/chart/TimeBucketSelector.svelte
- src/lib/chart/chart.css
- src/lib/content/PairInfoTable.svelte
- src/routes/__layout.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/_ChartSection.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/index.svelte
> chart UI improvements

- .env
- src/lib/chain/getApiError.ts
- src/lib/chain/maintenance.ts
- src/lib/config.ts
- src/routes/blog/[slug].svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/api-and-historical-data.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/index.svelte
- src/routes/trading-view/[chain]/[exchange]/export-data.svelte
- src/routes/trading-view/[chain]/[exchange_id].svelte
- src/routes/trading-view/[chain]/index.svelte
- src/routes/trading-view/[chain]/tokens/[token]/index.svelte
- src/routes/trading-view/__error.svelte
- src/routes/trading-view/blockchains.svelte
closes #100 
This PR addresses the `load` function change that was the cause of #100.
In addition, 7ecb29a31e1f0d67ab8c40adc6c59c7bb6643f69 makes `chainsUnderMaintenance` an ENV configurable value (JSON object). For now, a config change of this value requires a fresh `npm run build` in order to take effect.
> fix 500 errors

- src/routes/blog/rss.xml.ts
Set limit to all for now, we can work on generating the rss file with pagination, but I think this kind of optimization is no needed so far, we can also create a p2 ticket to do this at some point in the future. 
Now we can see listed the oldest ones too.
> Increase Limit blog post

- src/lib/chart/ChartIQ.svelte
- src/lib/chart/quoteFeed.ts
- src/lib/content/ExchangeInfoTable.svelte
- src/lib/content/TradingPairAPIExamples.svelte
- src/lib/helpers/exchange.ts
- src/lib/helpers/formatters.ts
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/InfoSummary.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/TimePeriodSummaryColumn.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/TimePeriodSummaryTable.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/api-and-historical-data/+page.svelte
closes #194 
This is mostly ready… just need some feedback on some questions I raised in #194.
> Uniswap V3 updates - exchange and pair pages

- src/routes/blog/SocialMetaTags.svelte
- src/routes/blog/image/[...file]/+server.ts
- create new Response object rather than returning fetched one
- fixes #202
> fix blog /blog/image endpoint

- src/lib/assets/icons/filter.svg
- src/lib/components/DropDown.svelte
- src/lib/components/NavPanel.svelte
- src/lib/components/TextInput.svelte
- src/lib/components/css/color.css
- src/lib/components/index.ts
- src/lib/search/Search.svelte
- src/lib/search/TradingEntityHit.svelte
- src/routes/search/+page.svelte
- src/routes/search/Filter.svelte
- src/routes/search/FilterPanel.svelte
- src/routes/search/SearchPanel.svelte
- src/routes/search/SortSelect.svelte
closes tradingstrategy-ai/design-system#57
> Advanced search page UI/UX upgrade

- src/lib/search/TradingEntityHit.svelte
Close trading-strategy/design-system#86
> style: Constant width for TradingEntityHit label

- src/routes/search/FilterPanel.svelte
- src/routes/search/SearchPanel.svelte
- src/routes/search/SearchPanel.test.ts
- src/routes/search/SortSelect.svelte
> advanced search UX improvements

- src/routes/+error.svelte
Closes https://github.com/tradingstrategy-ai/design-system/issues/91
> feat: Add logo to Error Page

- .env.test
- package-lock.json
- package.json
- src/lib/search/Search.test.ts
- src/lib/search/__mocks__/trading-entities.ts
- src/routes/search/+page.svelte
- src/routes/search/FilterPanel.svelte
- src/routes/search/RangeFilter.svelte
- src/routes/search/RangeFilter.test.ts
- src/routes/search/SearchPanel.svelte
- src/routes/search/SearchPanel.test.ts
- src/routes/search/SortSelect.svelte
- src/routes/search/SortSelect.test.ts
- tests/fixtures/typesense/collections/trading-entities/documents/search.json
- tests/integration/search.test.ts
- vite.config.js
This PR addresses a key UX issue with advanced search:
1. user searches for trading entities by entering a query and selecting filters / sort option
2. user clicks on a search result
3. user clicks "back" to return to search results
4. **result:**
- expected: search page retains the selections from step 1 above
- actual: search page selections revert to initial state
This is addressed by serializing the user's search selections into URL parameters. This has the added benefit of making a search _sharable_ – make search selections, copy the URL, open it in a new/different browser window – the search page will update to reflect the selections.
closes #25 
closes #53
> improve advanced search nav

- src/lib/components/AlertItem.svelte
- src/lib/components/AlertList.svelte
- src/lib/components/css/color.css
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
> style: Update Alerts appearance

- package-lock.json
- package.json
- src/lib/helpers/formatters.ts
- src/routes/strategy/[strategy_id]/performance/+layout.ts
- src/routes/strategy/[strategy_id]/performance/+page.svelte
- src/routes/strategy/[strategy_id]/performance/+page.ts
- src/routes/strategy/[strategy_id]/performance/PortfolioPerformanceChart.svelte
- src/routes/strategy/[strategy_id]/performance/SummaryStatistics.svelte
- src/routes/strategy/[strategy_id]/performance/interface.ts
- Include Plotly.js - financial flavour - from NPM https://www.npmjs.com/package/plotly.js-finance-dist
- Show portfolio value over time
- Show summary statistics
> Adding Performance page

- src/lib/components/Footer.svelte
Boosts Lighthouse accessibility score
> Add titles to links

- src/lib/components/DataBox.svelte
- src/lib/components/DataTable.svelte
- src/lib/components/PageHeading.svelte
- src/lib/components/SummaryBox.svelte
- src/routes/strategies/[strategy]/open-positions/[position]/+layout.ts
- src/routes/strategies/[strategy]/open-positions/[position]/+page.svelte
- src/routes/strategies/[strategy]/open-positions/[position]/trade-[trade]/+page.svelte
- src/routes/strategies/[strategy]/open-positions/[position]/trade-[trade]/+page.ts
- src/routes/strategies/[strategy]/open-positions/[position]/trade-[trade]/BlockchainExplorerLink.svelte
- src/routes/strategies/[strategy]/open-positions/[position]/trade-[trade]/TransactionStatus.svelte
- src/routes/strategies/[strategy]/open-positions/[position]/trade-[trade]/TransactionTable.svelte
- src/routes/strategy/[strategy_id]/open-positions/[position_id]/+page.ts
- src/routes/strategy/[strategy_id]/open-positions/[position_id]/trade-[trade_id]/+page.svelte
> Trade details page Theme 0.2 update

- src/routes/+layout.svelte
- src/routes/strategies/[strategy]/(nav)/StrategyNav.svelte
https://user-images.githubusercontent.com/37627284/207640567-8d290ae6-2d47-406b-a648-cb06b500ea66.mov
> feat: Sticky Strategies Nav for Desktop

- src/lib/components/DataBox.svelte
- src/lib/components/SummaryBox.svelte
- src/routes/strategies/[strategy]/(nav)/performance/+page.svelte
- src/routes/strategies/[strategy]/(nav)/performance/PortfolioPerformanceChart.svelte
- src/routes/strategies/[strategy]/(nav)/performance/SummaryStatistics.svelte
Close tradingstrategy-ai/design-system/issues/98
https://user-images.githubusercontent.com/37627284/207889895-5e6ee598-e1f5-4818-a94b-c1e5372c3785.mov
> feat: Strategy Performance page UI

- src/lib/components/SummaryBox.svelte
- src/routes/strategies/[strategy]/(nav)/decision-making/+page.svelte
Close tradingstrategy-ai/design-system/issues/100
https://user-images.githubusercontent.com/37627284/208681037-49e3be8c-eaed-4d09-8345-5b674a7689bf.mov
> feat: Decision Making UI/UX

- src/lib/components/AlertItem.svelte
- src/lib/components/AlertList.svelte
- src/routes/strategies/[strategy]/(nav)/+layout.svelte
Close #292
https://user-images.githubusercontent.com/37627284/208966304-2402c1c4-6d58-45b9-80fd-9551ec5eeafd.mov
> feat: Add Trade Executor beta Alert

- src/lib/components/BlogPostTile.test.ts
- src/lib/components/DateTime.svelte
- src/lib/components/DateTime.test.ts
> improve /strategies error handling

- src/routes/trading-view/[chain]/[exchange]/export-data/+page.svelte
- Make Uniswap v3 default to unfiltered because liquidity filter does not work because there is no data
> More Excel export fixes

- src/lib/components/HeroVideo.svelte
- src/lib/components/index.ts
- src/routes/+page.svelte
- src/routes/about/+page.svelte
> add explainer video to home and about pages

- src/lib/components/MenuItem.svelte
- src/routes/strategies/[strategy]/(nav)/+layout.svelte
- src/routes/strategies/[strategy]/(nav)/StrategyNav.svelte
> add position counts to strategy nav

- src/lib/helpers/exchange.ts
- src/lib/search/TradingEntityHit.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
> warnings for blacklisted exchanges

- src/lib/components/HeroBanner.svelte
- src/routes/blog/+page.svelte
> Adding HR and minor updates to blog header content

- src/lib/components/SummaryBox.svelte
- src/lib/components/css/table.css
- src/lib/momentum/TopTradesTable.svelte
Close tradingstrategy-ai/design-system#111
https://user-images.githubusercontent.com/37627284/214316298-0e342c4b-b1d0-46c3-81c8-c2ac929f0cc9.mov
> Improve Tables text sizing + Summary Box spacing

- src/routes/blog/BlogPostContent.svelte
Close tradingstrategy-ai/design-system#108
https://user-images.githubusercontent.com/37627284/214341549-3a0471aa-99d2-4801-a48d-80912a1b9aa9.mov
> style: Remove font weight hover effect causing layout jump

- package-lock.json
- package.json
- src/lib/blog/client.ts
- src/routes/+page.svelte
- src/routes/+page.ts
> upgrade Ghost client lib and API version

- src/lib/components/TextInput.svelte
- src/lib/components/css/text-field.css
- src/lib/components/css/themes/index.css
- src/lib/components/css/themes/theme-dark.css
- src/lib/components/css/themes/theme-light.css
- src/lib/components/css/typography.css
- src/lib/newsletter/OptInBanner.svelte
- src/lib/newsletter/SubscribeForm.svelte
- src/routes/search/SearchPanel.svelte
Close tradingstrategy-ai/design-system#113
https://user-images.githubusercontent.com/37627284/214702718-2fa20c48-4cec-4033-b09b-13699a6ba108.mov
> Improve Inputs' contrast + add monospace font for Newsletter Subscribe Form

- src/lib/explorer/PairExplorer.svelte
- src/routes/trading-view/[chain]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/InfoSummary.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
- src/routes/trading-view/[chain]/tokens/[token]/+page.svelte
- src/routes/trading-view/trading-pairs/+page.svelte
closes #297 
Note the `FIXME` here:
https://github.com/tradingstrategy-ai/frontend/blob/297-uniswap-table-fixes/src/routes/trading-view/%5Bchain%5D/%5Bexchange%5D/%2Bpage.svelte#L16-L21
Opened tradingstrategy-ai/backend#110 to address this.
> 297 uniswap table fixes

- src/lib/components/css/typography.css
- src/routes/blog/BlogPostContent.svelte
> Improve headings sizing for Blog Posts

- package-lock.json
- package.json
fixes #331
This was due to a bug in `v8.7.0` of ChartIQ. Upgrading to latest `v8.8.4` seems to have resolved it.
> upgrade ChartIQ to 8.8.4

- src/lib/components/Footer.svelte
- src/lib/components/SocialIcon.svelte
> feat: Add GitHub icon to footer + improve responsive styles

- package-lock.json
- package.json
> fix v107 node.js crashing on Prod

- src/lib/chart/ChartIQ.svelte
Close tradingstrategy-ai/design-system#76
https://user-images.githubusercontent.com/37627284/223729021-af8758d2-dd1f-452c-aeb7-639dc4101493.mov
> style: Better aspect ratio for Charts in Mobile

- src/lib/components/css/table.css
- src/lib/components/datatable/DataTable.svelte
- src/lib/components/datatable/TableBody.svelte
- src/lib/components/datatable/TableRow.svelte
Close tradingstrategy-ai/design-system#119
We have 2 options:
https://user-images.githubusercontent.com/37627284/223732944-be3519f1-d293-43a8-85eb-59f9ba9e49f4.mov
> feat: Responsive table items numeration with CSS increments

- package-lock.json
- package.json
- src/lib/components/EntitySymbol.svelte
- src/lib/helpers/chain.ts
- src/lib/wallet/ConnectWallet.svelte
- src/lib/wallet/WalletSummary.svelte
- src/routes/wizard/+layout.ts
- src/routes/wizard/connect-wallet/connect/+page.svelte
> MetaMask connect wallet integration

- src/lib/wallet/WalletBalance.svelte
- src/lib/wallet/WalletSummary.svelte
- src/lib/wallet/utils.ts
> Display native chain currency and USDC wallet balances

- src/lib/helpers/chain.ts
- src/lib/wallet/ConnectWallet.svelte
- src/lib/wallet/WalletSummary.svelte
- src/lib/wallet/client.ts
- src/routes/strategies/[strategy]/(nav)/+page.svelte
- src/routes/wizard/+layout.svelte
- src/routes/wizard/+layout.ts
- src/routes/wizard/connect-wallet/+page.ts
- src/routes/wizard/connect-wallet/balance/+page.svelte
- src/routes/wizard/connect-wallet/connect/+page.svelte
- src/routes/wizard/connect-wallet/introduction/+page.svelte
- src/routes/wizard/connect-wallet/success/+page.svelte
- src/routes/wizard/deposit/+page.ts
- src/routes/wizard/deposit/balance/+page.svelte
- src/routes/wizard/deposit/connect/+page.svelte
- src/routes/wizard/deposit/introduction/+page.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/deposit/success/+page.svelte
- src/routes/wizard/wizardState.ts
> wallet wizard - detect / change network

- src/routes/search/FilterPanel.svelte
- src/routes/search/NumericFilter.svelte
- tests/integration/search.test.ts
> Add pool swap fee filter

- src/ambient.d.ts
- src/lib/wallet/InvestorWidget.svelte
- src/lib/wallet/WalletBalance.svelte
- src/lib/wallet/client.ts
- src/lib/wallet/utils.ts
- src/routes/strategies/[strategy]/(nav)/+page.svelte
- src/routes/strategies/[strategy]/+layout.ts
> use `metadata.on_chain_data` for asset management info

- src/lib/components/AlertItem.svelte
- src/lib/components/AlertList.svelte
- src/lib/components/MoneyInput.svelte
- src/lib/eth-defi/eip-3009.ts
- src/lib/eth-defi/enzyme.ts
- src/lib/wallet/InvestorWidget.svelte
- src/lib/wallet/WalletBalance.svelte
- src/lib/wallet/WalletDeposit.svelte
- src/lib/wallet/utils.ts
- src/routes/wizard/deposit/balance/+page.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/deposit/success/+page.svelte
> deposit wizard UX enhancements

- package-lock.json
- package.json
- src/lib/wallet/WalletSummary.svelte
- src/lib/wallet/client.ts
- src/routes/wizard/deposit/payment/+page.svelte
> fix WalletConnect sign/transact issues

- src/lib/components/MoneyInput.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
> fix MoneyInput value conversion bug

- src/routes/sitemap.xml/+server.ts
- fixes https://github.com/tradingstrategy-ai/docs/issues/26
> fix sitemap link

- .github/workflows/javascript.yml
- src/lib/wallet/WrongNetwork.svelte
- vite.config.ts
> Fix CI test flakiness

- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionTable.svelte
Close tradingstrategy-ai/design-system/issues/138
https://github.com/tradingstrategy-ai/frontend/assets/37627284/d43a10bd-95b6-49f4-9e04-03ad8fc40558
> feat: Positions Table sizing improvements

- src/routes/strategies/StrategyTile.svelte
> Added strategy tile logos

- src/lib/components/Tooltip.svelte
- src/routes/strategies/KeyMetric.svelte
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/+page.svelte
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/FlagCell.svelte
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/position-flags.ts
- Add error markers to the position list
Still need
- Error markers on position page
- Error markers on trade pages
> Position list error markers

- src/lib/components/SummaryBox.svelte
- src/lib/components/css/table.css
- src/lib/explorer/LendingReserveTable.svelte
- src/lib/explorer/lending-reserve-client.ts
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/trading-view/[chain]/+page.svelte
- src/routes/trading-view/[chain]/+page.ts
- src/routes/trading-view/[chain]/TopEntities.svelte
- src/routes/trading-view/[chain]/TopExchanges.svelte
- src/routes/trading-view/[chain]/TopPairs.svelte
- src/routes/trading-view/[chain]/TopReserves.svelte
- src/routes/trading-view/[chain]/TopTokens.svelte
- src/routes/trading-view/[chain]/TradingEntitiesTable.svelte
- src/routes/trading-view/[chain]/exchanges/+page.svelte
- src/routes/trading-view/[chain]/exchanges/+page.ts
- src/routes/trading-view/[chain]/lending-reserves/+page.svelte
- src/routes/trading-view/[chain]/lending-reserves/+page.ts
- src/routes/trading-view/[chain]/tokens/+page.svelte
- src/routes/trading-view/[chain]/trading-pairs/+page.svelte
- src/routes/trading-view/[chain]/trading-pairs/+page.ts
- src/routes/trading-view/lending-reserves/+page.svelte
- src/routes/trading-view/lending-reserves/+page.ts
close tradingstrategy-ai/design-system#140
close #379 
close #214
https://github.com/tradingstrategy-ai/frontend/assets/35901/d6bb56f0-db4c-47bf-9895-473a71f6a380
https://github.com/tradingstrategy-ai/frontend/assets/35901/bba67f6c-4cb3-45d7-993d-cb6dd0050303
> Update layout of trading entities tables on chain details

- src/lib/components/index.ts
- src/routes/strategies/StrategyTile.svelte
- src/routes/strategies/StrategyTile.test.ts
> MetaMask Icon for Hot Wallet based strategies

- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
> Add compatibility layer for xyliquidity/candles APIs

- src/lib/helpers/formatters.ts
- src/lib/trade-executor/state/position-data.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/+page.svelte
- Mainly to workaround data formatting
- Have separate tooltips for missing data points
> Position page data fixes

- src/lib/components/MoneyInput.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/WalletBalance.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/deposit-status/+page.svelte
- src/routes/wizard/redeem/success/+page.svelte
> Use consistent balance formatting in investor wizards

- src/lib/search/TradingEntityHit.svelte
- src/routes/search/FacetFilter.svelte
- src/routes/search/SortSelect.svelte
- src/routes/search/SortSelect.test.ts
> Search lending reserves UI

- package-lock.json
- package.json
- src/lib/wallet/InvestorWidget.svelte
- src/routes/wizard/+layout.svelte
- src/routes/wizard/+layout.ts
- src/routes/wizard/WizardActions.svelte
- src/routes/wizard/WizardNavItem.svelte
- src/routes/wizard/connect-wallet/+layout.ts
- src/routes/wizard/connect-wallet/balance/+page.svelte
- src/routes/wizard/connect-wallet/connect/+page.svelte
- src/routes/wizard/connect-wallet/introduction/+page.svelte
- src/routes/wizard/connect-wallet/store.ts
- src/routes/wizard/connect-wallet/success/+page.svelte
- src/routes/wizard/deposit/+layout.ts
- src/routes/wizard/deposit/balance/+page.svelte
- src/routes/wizard/deposit/connect/+page.svelte
- src/routes/wizard/deposit/introduction/+page.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/deposit/store.ts
- src/routes/wizard/deposit/success/+page.svelte
- src/routes/wizard/redeem/+layout.ts
- src/routes/wizard/redeem/connect/+page.svelte
- src/routes/wizard/redeem/deposit-status/+page.svelte
- src/routes/wizard/redeem/introduction/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
- src/routes/wizard/redeem/store.ts
- src/routes/wizard/redeem/success/+page.svelte
- src/routes/wizard/redeem/success/+page.ts
- src/routes/wizard/store.ts
> Persist wizard state using sessionStorage

- src/lib/components/Section.svelte
- src/lib/wallet/WalletInfo.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
> Add max deposit/redeem control

- docs/aave-utilities.md
- package-lock.json
- package.json
- src/lib/explorer/lending-reserve-client.ts
- src/lib/helpers/lending-reserve.ts
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.ts
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/InfoTable.svelte
> Display additional reserve stats

- src/lib/chart/HudRow.svelte
- src/lib/chart/ReserveInterestChart.svelte
- src/lib/chart/studies.ts
> Improve reserve chart lines

- svelte.config.js
> Fix reserves SSR 500 error

- src/lib/chart/PairCandleChart.svelte
- src/lib/chart/ReserveInterestChart.svelte
- src/lib/chart/quote-feed.ts
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
> Display pair TVL chart when available

- src/lib/__mocks__/config.ts
- src/lib/chart/chart.css
- src/routes/strategies/ChartThumbnail.svelte
- src/routes/strategies/StrategyTile.svelte
- src/routes/strategies/StrategyTile.test.ts
- convert to ChartIQ
- use 'mountain' chart style
close #489
> Strategy tile chart updates

- src/lib/components/Section.svelte
- src/lib/config.ts
- src/routes/+error.svelte
- src/routes/+layout.svelte
- src/routes/ErrorPageInfo.svelte
- src/routes/MaintenanceNotice.svelte
- src/routes/data/chains/+server.ts
- src/routes/data/chains/cache.json
- src/routes/strategies/+page.svelte
- src/routes/strategies/StrategyTile.svelte
- tests/fixtures/chains.json
- add `chains` fixture data - required for dev mode
- add fallback chains cache (when backend not available)
- make maintenance notice configurable: TS_PUBLIC_MAINTENANCE_NOTICE
> Make maintance notice configurable

- src/routes/strategies/[strategy]/(nav)/logs/LogEntriesList.svelte
- src/routes/strategies/[strategy]/(nav)/logs/LogEntry.svelte
> display strategy error traceback when available

- package-lock.json
- package.json
- src/lib/wallet/client.ts
close #590
- @wagmi/core -> 1.4.2
- @walletconnect/modal -> 2.6.2
- @web3modal/ethereum -> 2.7.1
- viem -> 1.10.14
> upgrade web3 frameworks (wagmi, walletconnect, viem)

- src/ambient.d.ts
- src/lib/components/DataBox.svelte
- src/lib/components/Timestamp.svelte
- src/lib/components/UpDownIndicator.svelte
- src/lib/helpers/formatters.test.ts
- src/lib/helpers/formatters.ts
- src/lib/trade-executor/helpers/formatters.ts
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/WalletBalance.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/TradeTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/trade-[trade]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/api-and-historical-data/APIExamples.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/InfoTable.svelte
- src/routes/trading-view/[chain]/tokens/[token]/InfoSummary.svelte
- src/routes/trading-view/[chain]/tokens/[token]/InfoTable.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/deposit-status/+page.svelte
- src/routes/wizard/redeem/success/+page.svelte
- Group variables based on what makes sense
- Show % and delay changes
- More changes coming after these changes have been merged
- Please feel free to adjust layout (colours, padding, font sizes)
> Update the trade page stats and layout

- src/lib/components/css/table.css
- src/lib/components/datatable/DataTable.svelte
- src/lib/components/datatable/TableBody.svelte
- src/lib/components/datatable/TableRow.svelte
- src/lib/explorer/ExchangeTable.svelte
- src/lib/explorer/LendingReserveTable.svelte
- src/lib/explorer/PairTable.svelte
- src/lib/explorer/TokenTable.svelte
- src/lib/momentum/MomentumTable.svelte
- src/lib/momentum/TopTradesTable.svelte
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/TradeTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/trade-[trade]/TransactionTable.svelte
Close tradingstrategy-ai/design-system#130
> feat: Table sizing

- src/lib/trade-executor/strategy/runtime-state.ts
- src/routes/glossary/api/+server.ts
- src/routes/strategies/+page.server.ts
- src/routes/strategies/+page.ts
> Cache trade-executor metadata

- src/lib/wallet/ConnectWallet.svelte
- src/lib/wallet/client.ts
fixes tradingstrategy-ai/scratchpad#66
> Fix wallet connection bug

- package-lock.json
- package.json
- src/lib/swrCache.ts
- src/routes/+layout.ts
- src/routes/data/chains/+server.ts
- src/routes/glossary/api/+server.ts
- src/routes/strategies/+page.server.ts
- tests/e2e/data/chains.test.ts
towards #607
Convert pre-rendered chains endpoint to use SWR cache.
> Fix local node build issue

- .github/workflows/javascript.yml
- Dockerfile
- docker-compose.yml
- package-lock.json
- package.json
- src/hooks.client.ts
- src/hooks.server.ts
- src/lib/config.ts
- src/lib/header/SiteMode.svelte
- src/routes/sentry-test/+page.server.ts
- src/routes/sentry-test/+page.svelte
- src/routes/wizard/redeem/success/+page.ts
- vite.config.ts
closes #609
- use new(ish) Sentry SvelteKit plugin
- add client-side error handler
- add sourcemap uploads
> Improve Sentry integration

- src/lib/components/MenuItem.svelte
- src/lib/header/Navbar.svelte
- src/routes/HomeHeroBanner.svelte
- src/routes/about/Feature.svelte
- src/routes/about/Platform.svelte
- src/routes/community/+page.svelte
- src/routes/glossary/[slug]/+page.svelte
- src/routes/sentry-test/+page.svelte
- src/routes/trading-view/+page.svelte
- src/routes/trading-view/[chain]/+page.svelte
- src/routes/trading-view/[chain]/SummaryDataTile.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/InfoSummary.svelte
- src/routes/trading-view/[chain]/[exchange]/InfoTable.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/api-and-historical-data/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/api-and-historical-data/APIExamples.svelte
- src/routes/trading-view/[chain]/[exchange]/export-data/+page.svelte
- src/routes/trading-view/[chain]/tokens/[token]/+page.svelte
- src/routes/trading-view/[chain]/tokens/[token]/InfoTable.svelte
- src/routes/trading-view/backtesting/+page.svelte
fixes #614
Add `rel="external"` to all external links
> Fix external links

- src/lib/explorer/PairTable.svelte
- src/lib/explorer/pair-client.ts
- src/lib/helpers/formatters.ts
- src/lib/search/components/Search.svelte
- src/lib/search/components/SearchHit.svelte
- src/routes/search/Filter.svelte
- src/routes/search/FilterPanel.svelte
- src/routes/search/NumericFilter.svelte
- src/routes/search/RangeFilter.svelte
- src/routes/search/SortSelect.svelte
- src/routes/search/SortSelect.test.ts
- src/routes/trading-view/[chain]/+page.svelte
- src/routes/trading-view/[chain]/TopPairs.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/tokens/[token]/+page.svelte
- src/routes/trading-view/[chain]/trading-pairs/+page.svelte
- src/routes/trading-view/[chain]/trading-pairs/+page.ts
- src/routes/trading-view/trading-pairs/+page.svelte
- src/routes/trading-view/trading-pairs/+page.ts
- tests/fixtures/pairs.json
- tests/integration/search.test.ts
- tests/integration/trading-view/token-details.test.ts
> Filter and sort trading pairs by TVL

- src/lib/components/Button.svelte
- src/lib/components/Icon.svelte
- src/lib/trade-executor/strategy/runtime-state.ts
- src/lib/wallet/DepositBalance.svelte
- src/lib/wallet/DepositWarning.svelte
- src/lib/wallet/MyDeposits.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/index.ts
- src/routes/strategies/StrategyTile.svelte
- src/routes/strategies/[strategy]/(nav)/+page.svelte
- src/routes/strategies/[strategy]/(nav)/StrategyNav.svelte
- src/routes/strategies/[strategy]/(nav)/SummaryBox.svelte
> Make deposit widget collapsable on mobile

- src/lib/helpers/formatters.ts
- src/lib/trade-executor/helpers/formatters.test.ts
- src/lib/trade-executor/helpers/formatters.ts
- src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionTable.svelte
> Fix profitability formatting (1 fractional digit)

- src/lib/components/SegmentedControl.svelte
- src/lib/trade-executor/state/statistics.ts
- src/routes/strategies/[strategy]/(nav)/performance/+page.svelte
> add live/backtesting toggle to performance page

- src/lib/components/PageHeader.svelte
- src/lib/components/SegmentedControl.svelte
- src/routes/strategies/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/InfoTable.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
> Exchange details page refresh

- .env
- src/app.d.ts
- src/hooks.server.ts
- src/lib/__mocks__/config.ts
- src/lib/config.ts
- src/lib/helpers/geo.test.ts
- src/lib/helpers/geo.ts
- src/lib/wallet/MyDeposits.svelte
- src/routes/+layout.server.ts
- src/routes/diagnostics/+page.server.ts
- src/routes/strategies/+layout.server.ts
- src/routes/strategies/+page.server.ts
- src/routes/strategies/[strategy]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
- src/routes/wizard/deposit/+layout.ts
- tests/integration/strategies/index.test.ts
> Block strategy viewing and deposits in specified countries

- src/lib/components/Tooltip.svelte
- src/routes/strategies/[strategy]/+layout.svelte
- src/routes/strategies/[strategy]/StrategyNav.svelte
- src/routes/strategies/[strategy]/fees/+page.svelte
> Add strategy fees page

- src/lib/chart/ChartIQ.svelte
- src/lib/chart/ReserveInterestChart.svelte
- src/lib/components/EntitySymbol.svelte
- src/lib/explorer/ExchangeTable.svelte
- src/lib/explorer/LendingReserveTable.svelte
- src/lib/explorer/PairSymbolCell.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/WalletBalance.svelte
- src/routes/strategies/StrategyTile.svelte
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/InfoTable.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/deposit-status/+page.svelte
- src/routes/wizard/redeem/success/+page.svelte
> Lending reserve details page refresh

- src/lib/components/Footer.svelte
- src/lib/header/Navbar.svelte
- src/routes/strategies/+page.svelte
- src/routes/trading-view/+page.svelte
- Prepare to take open strategies live
- Update the website footer as by new operator
- Update nav bar
- Some tidy up of texts here and there
> Open strategies live

- src/lib/components/MoneyInput.svelte
- src/lib/eth-defi/enzyme.ts
- src/lib/eth-defi/helpers.ts
- src/lib/wallet/DepositBalance.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/VaultBalance.svelte
- src/lib/wallet/WalletBalance.svelte
- src/routes/wizard/deposit/balance/+page.svelte
- src/routes/wizard/deposit/introduction/+page.svelte
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/introduction/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
- src/routes/wizard/redeem/success/+page.svelte
> use USDC.e label

- src/lib/eth-defi/eip-3009.ts
> fix wallet EIP-3009 signature

- src/lib/trade-executor/strategy/runtime-state.ts
- src/routes/+page.server.ts
- src/routes/+page.svelte
- src/routes/+page.ts
- src/routes/HomeHeroBanner.svelte
- src/routes/strategies/+page.server.ts
> Add "Top strategies" to front page

- src/lib/actions/viewport.ts
- src/lib/components/Dialog.svelte
- src/lib/components/Header.svelte
- src/lib/components/NavPanel.svelte
- src/lib/components/css/breakpoints.css
- src/lib/header/ColorModePicker.svelte
- src/lib/helpers/scroll.ts
- src/lib/search/components/Search.svelte
- src/routes/wizard/WizardHeader.svelte
- src/routes/wizard/deposit/tos/+page.svelte
> Improve ToS mobile UX

- src/routes/+page.svelte
- src/routes/strategies/StrategyTile.svelte
> Fix strategy tile layout issues

- src/lib/trade-executor/strategy/runtime-state.ts
- src/lib/trade-executor/strategy/summary.ts
- tests/fixtures/strategies/enzyme-polygon-multipair/metadata.json
- tests/integration/strategies/index.test.ts
> Sort strategies based on sort_priority

- src/lib/header/Navbar.svelte
- src/routes/+page.svelte
- Nav bar: Docs -> developers
- Live time
> Some minor text updates for the front page for the launch

- src/lib/trade-executor/strategy/configuration.ts
- src/routes/strategies/tvl/+server.ts
- Add a JSON endpoint to get (id, chain, address) tuples of all strategies
- Export some misc. other data while at it
- Will be consumed by DefiLlama
> Add /strategies/tvl API for DefiLlama

- src/lib/trade-executor/components/KeyMetric.svelte
- src/lib/trade-executor/statistics/key-metric.ts
- src/lib/trade-executor/strategy/runtime-state.ts
- src/routes/strategies/StrategyTile.svelte
- src/routes/strategies/[strategy].ipynb/+server.ts
- src/routes/strategies/[strategy]/+layout.ts
- tests/fixtures/strategies/enzyme-polygon-matic-usdc/metadata.json
> Fix strategy parse error

- src/lib/components/MoneyInput.svelte
- src/lib/eth-defi/enzyme.ts
- src/lib/eth-defi/helpers.ts
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
> use real minSharesQuantity in payment tx

- src/lib/explorer/LendingReserveLabel.svelte
- src/lib/explorer/LendingReserveTable.svelte
- src/lib/helpers/lending-reserve.ts
- src/routes/trading-view/[chain]/TopEntities.svelte
> Add support for Aave v2 lending reserves

- src/hooks.server.ts
- src/routes/trading-view/backtesting/+page.svelte
> Fix backtest download links

- src/lib/trade-executor/state/loan.ts
- src/routes/strategies/[strategy]/+layout.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/trade-[trade=integer]/+page.svelte
> Fix ETH breakout state parse errors

- src/lib/components/DataBox.svelte
- src/lib/trade-executor/helpers/formatters.test.ts
- src/lib/trade-executor/helpers/formatters.ts
- src/lib/trade-executor/helpers/profit.ts
- src/lib/trade-executor/state/position-info.ts
- src/lib/trade-executor/state/trade-info.ts
- src/lib/trade-executor/state/trading-pair-info.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/TradeTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/trade-[trade=integer]/+page.svelte
> Update positions/trades to support credit positions

- src/lib/chart/ChartContainer.svelte
- src/lib/chart/PerformanceChart.svelte
- src/routes/strategies/+page.server.ts
- src/routes/strategies/+page.svelte
- src/routes/strategies/ChartThumbnail.svelte
- src/routes/strategies/StrategyTvlChart.svelte
- src/routes/strategies/[strategy]/+page.svelte
- src/routes/strategies/[strategy]/netflow/+page.svelte
- src/routes/strategies/[strategy]/performance/+page.svelte
> Add live strategies TVL chart

- src/routes/+page.svelte
- src/routes/FeaturedStrategies.svelte
- src/routes/StrategyDifferentiator.svelte
> Add strategy differentiators to front page

- src/lib/trade-executor/state/identifier.ts
- src/lib/trade-executor/state/position-info.ts
- src/routes/strategies/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/TradeTable.svelte
> add credit position interest rate

- src/lib/chart/PairCandleChart.svelte
- src/lib/components/css/index.css
- src/lib/components/css/metrics-table.css
- src/lib/helpers/formatters.test.ts
- src/lib/helpers/formatters.ts
- src/lib/trade-executor/helpers/formatters.test.ts
- src/lib/trade-executor/helpers/formatters.ts
- src/lib/trade-executor/state/position-info.test.ts
- src/lib/trade-executor/state/position-info.ts
- src/lib/trade-executor/state/trade-info.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/OtherMetrics.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/PositionProfitability.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/PositionSummary.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/TradeTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/trade-[trade=integer]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
> Reformat position details using metrics tables

- src/lib/trade-executor/strategy/configuration.ts
- src/routes/strategies/[strategy]/fees/+page.svelte
- redesign fees table
- make fee values configurable
- customize "Beta info" and add fee tooltips
- close #774
> Make strategy fees configurable

- src/routes/strategies/[strategy]/fees/+page.svelte
- improve layout based on Teeumu's feedback
- remove "Beta info" section (per Mikko)
- improve tooltips
> Strategy fees improvements

- src/lib/components/EntitySymbol.svelte
- src/lib/search/trading-entities.ts
- src/lib/search/typesense-client.ts
- src/routes/trading-view/[chain]/[exchange]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte
- src/routes/trading-view/[chain]/tokens/[token]/+page.svelte
- src/routes/trading-view/[chain]/tokens/[token]/+page.ts
- src/routes/trading-view/[chain]/tokens/[token]/InfoSummary.svelte
- src/routes/trading-view/[chain]/tokens/[token]/InfoTable.svelte
close #641
- add blockchain logo to token details page
- fix trading entity subtitle wrapping issue
- add lending reserves links to token details page
- style "inclusion criteria" text consistently
> Token details refresh

- src/routes/trading-view/[chain]/+page.svelte
- src/routes/trading-view/[chain]/+page.ts
- src/routes/trading-view/[chain]/TopReserves.svelte
- src/routes/trading-view/[chain]/TopTokens.svelte
- src/routes/trading-view/[chain]/lending/+page.svelte
> Sort top lending reserves by TVL

- src/app.d.ts
- src/lib/chart/PairCandleChart.svelte
- src/lib/chart/helpers.ts
- src/lib/components/Dialog.svelte
- src/lib/components/SegmentedControl.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain]/[exchange]/[pair]/+page.ts
- src/routes/trading-view/[chain]/[exchange]/[pair]/ChartSection.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte
- src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.ts
- fix Safari visual bug with dialogs
- fix unhandled dialog.close() error
- fix chart.masterData.length error
- ensure timeBucket URL param is valid
towards #791
fixes #790
> Fix common Sentry errors

- src/lib/chart/ChartContainer.svelte
- src/lib/chart/PerformanceChart.svelte
- src/routes/strategies/[strategy]/+page.svelte
> add "Max" timespan to strategy performance charts

- src/lib/trade-executor/strategy/configuration.ts
- src/routes/+page.server.ts
- src/routes/FeaturedStrategies.svelte
close #800
- add `frontpage` flag to determine front page strategies
- improve "Open strategies" layout on front page
> Update front page "Open strategies"

- src/lib/chart/ChartContainer.svelte
- src/lib/chart/PerformanceChart.svelte
- src/routes/strategies/StrategyTvlChart.svelte
- src/routes/strategies/[strategy]/+page.svelte
- src/routes/strategies/[strategy]/netflow/+page.svelte
- src/routes/strategies/[strategy]/performance/+page.svelte
close #807
- fix "max" chart period performance metric
- fix period performance metric for incomplete chart window
> Fix chart period performance metric

- src/lib/chart/ChartContainer.svelte
- src/lib/chart/ChartIQ.svelte
- src/lib/chart/PerformanceChart.svelte
- src/lib/chart/quote-feed.ts
- src/lib/chart/studies.ts
- src/lib/trade-executor/helpers/benchmarks.ts
- src/routes/strategies/[strategy]/+page.svelte
> Add strategy performance benchmarks v1

- src/lib/explorer/TradingDescription.svelte
- src/lib/trade-executor/state/position-info.ts
- src/lib/trade-executor/state/position-tooltips.ts
- src/lib/trade-executor/state/position.ts
- src/lib/trade-executor/state/trade-info.test.ts
- src/lib/trade-executor/state/trade-info.ts
- src/lib/trade-executor/state/trading-pair-info.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/FlagCell.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/OtherMetrics.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/PositionProfitability.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/PositionSummary.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/TradeTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/trade-[trade=integer]/+page.svelte
towards #812
- improve failed trade/position indicators & alerts
- add "profitability data inconsistent" remark
- simplify position/trade view model factory methods
> Add position remark for inconsistent profit data

- src/lib/trade-executor/helpers/vault.ts
- src/lib/trade-executor/strategy/configuration.ts
- src/lib/wallet/MyDeposits.svelte
- src/routes/strategies/[strategy]/vault/+page.svelte
> Add "Deposit at Enzyme" temporary hack

- src/lib/eth-defi/helpers.ts
- src/lib/helpers/progressbar.ts
- src/routes/wizard/deposit/payment/+page.svelte
- src/routes/wizard/deposit/payment/PaymentError.svelte
- src/routes/wizard/deposit/tos/+page.svelte
- src/routes/wizard/redeem/deposit-status/+page.svelte
- src/routes/wizard/redeem/shares-redemption/+page.svelte
- src/routes/wizard/redeem/success/+page.svelte
- src/routes/wizard/store.ts
- check if allowance has already been approved
- use chain-specific estimated block duration
- refactor error handling / user error messages
- ensure wizard.data is always set
close #833
close #834
> USDT payment flow improvements

- src/lib/components/TargetableLink.svelte
- src/lib/components/datatable/TableBody.svelte
- src/lib/momentum/MomentumTable.svelte
- src/routes/trading-view/[chain=slug]/TradingEntitiesTable.svelte
- src/routes/trading-view/top-list/[direction=momentum]/+page.svelte
- src/routes/trading-view/top-list/[direction=momentum]/+page.ts
> fix Mobile Safari tr.targetable bug

- .github/workflows/javascript.yml
- tests/integration/index.test.ts
Figure out why integration tests aren't passing in CI
> Troubleshoot build

- src/lib/assets/tos/2024-12-19.txt
- src/lib/components/Footer.svelte
close #871
- add new Terms of Service version 2024-12-19.txt
- update footer (official name / location)
> Update Terms of Service and footer

- src/lib/explorer/ExchangeTable.svelte
- src/routes/trading-view/[chain=slug]/+page.ts
close #874
- sort "Unknown 0x…" DEXes last on exchange table
- filter "Unknown 0x…" DEXes on chain details page
> Sort unknown DEXes last

- src/lib/trade-executor/helpers/tos.ts
> update ToS versions and acceptance messages

- src/lib/components/SegmentedControl.svelte
- src/routes/strategies/+page.svelte
> Add Current|Archived filter

- src/lib/helpers/option-group.svelte.ts
- src/lib/trade-executor/components/ChainFilter.svelte
- src/routes/FeaturedStrategies.svelte
- src/routes/strategies/+page.svelte
persist strategy filter options in URL params
> Improve strategy filters

- src/routes/strategies/[strategy]/[status=positionStatus]-positions/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/PositionTable.svelte
> update open positions sort/pagination

- src/lib/components/DataBox.svelte
- src/lib/components/MoneyInput.svelte
- src/lib/eth-defi/helpers.ts
- src/lib/eth-defi/schemas/token.ts
- src/lib/trade-executor/vaults/base.ts
- src/lib/trade-executor/vaults/enzyme/index.ts
- src/lib/trade-executor/vaults/lagoon/index.ts
- src/lib/trade-executor/vaults/velvet/index.ts
- src/lib/wallet/DepositBalance.svelte
- src/lib/wallet/MyDeposits.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/VaultBalance.svelte
- src/lib/wallet/WalletBalance.svelte
- src/routes/strategies/[strategy]/(wizard)/deposit/+layout.ts
- src/routes/strategies/[strategy]/(wizard)/deposit/success/+page.svelte
- src/routes/strategies/[strategy]/(wizard)/redeem/+layout.ts
- src/routes/strategies/[strategy]/(wizard)/redeem/deposit-status/+page.svelte
- src/routes/strategies/[strategy]/+layout.svelte
- src/routes/strategies/[strategy]/+layout.ts
- src/routes/strategies/[strategy]/+page.svelte
- src/routes/strategies/[strategy]/StrategyNav.svelte
- src/routes/strategies/[strategy]/vault/+page.svelte
- src/routes/strategies/[strategy]/vault/+page.ts
Use vault adapters when rendering [strategy]/vault page
close #888
close #867
> Vault page updates for Velvet and Lagoon

- src/routes/strategies/+layout.server.ts
> Geo-block demo URL

- src/lib/wallet/ConnectWallet.svelte
- src/lib/wallet/DepositBalance.svelte
- src/lib/wallet/MyDeposits.svelte
- src/lib/wallet/PendingDepositInfo.svelte
- src/lib/wallet/TokenBalance.svelte
- src/lib/wallet/client.ts
- fix PostCSS transform warning
- switch to correct chain after connecting wallet
- fix MyDeposits balance invalidation
> Fix several issues with v410

- src/lib/eth-defi/helpers.ts
- src/lib/helpers/retry-counter.ts
- src/lib/trade-executor/helpers/date.ts
- src/lib/trade-executor/schemas/summary.ts
- src/lib/trade-executor/vaults/base.ts
- src/lib/trade-executor/vaults/enzyme/index.ts
- src/lib/trade-executor/vaults/lagoon/index.ts
- src/lib/wallet/MyDeposits.svelte
- src/lib/wallet/PendingExchangeInfo.svelte
- src/routes/strategies/[strategy]/(wizard)/deposit/+layout.ts
- src/routes/strategies/[strategy]/(wizard)/deposit/payment/+page.svelte
- src/routes/strategies/[strategy]/(wizard)/deposit/payment/PaymentError.svelte
- src/routes/strategies/[strategy]/(wizard)/redeem/+layout.ts
- src/routes/strategies/[strategy]/(wizard)/redeem/shares-redemption/+page.svelte
- src/routes/strategies/[strategy]/(wizard)/redeem/shares-redemption/RedemptionError.svelte
- src/routes/strategies/[strategy]/(wizard)/redeem/success/+page.svelte
- improve PendingExchangeInfo reactivity
- remove helpers only used by vaults
- hide PendingExchangeInfo if geoBlocked or wrongNetwork
- update "settlement" language in two more places
- use common patterns in deposit/redeem wizards
- add Base value to getExpectedBlockTime helper
- display estimated settlement time in pending exchange info
> Vault / wizard improvements

- src/lib/components/datatable/DataTable.svelte
- src/lib/components/datatable/TableBody.svelte
- src/lib/eth-defi/helpers.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/+page.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/+page.ts
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/PositionTable.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/RemarksCell.svelte
- src/routes/strategies/[strategy]/[status=positionStatus]-positions/ReservesRow.svelte
> Add reserves to open positions

- src/lib/chart/PairCandleChart.svelte
- src/lib/chart/ReserveInterestChart.svelte
- src/lib/chart/quote-feed.ts
- src/routes/trading-view/[chain=slug]/[exchange]/[pair]/+page.svelte
- src/routes/trading-view/[chain=slug]/[exchange]/[pair]/ChartSection.svelte
> hide 1h TVL chart for base uniswap-v3 pairs

- src/lib/charts/CandleSeries.svelte
- src/lib/charts/CandleVolumeSeries.svelte
- src/lib/charts/ChartHeader.svelte
- src/lib/charts/PairCandleChart.svelte
- src/lib/charts/ReserveInterestChart.svelte
- src/lib/charts/TvChart.svelte
- src/lib/charts/candle-data-feed.svelte.ts
- src/lib/charts/helpers.ts
- src/lib/charts/types.ts
- src/routes/trading-view/[chain=slug]/lending/[protocol]/[reserve]/+page.svelte
> TradingView reserve interest chart

- src/routes/strategies/[strategy]/[status=positionStatus]-positions/RemarksCell.svelte
> update "F" / "Failed" position flag to "I" / "Issues"

- src/routes/blog/+page.svelte
- src/routes/blog/[slug=slug]/BlogPostContent.svelte
- src/routes/blog/[slug=slug]/TableOfContents.svelte
- tests/e2e/blog.test.ts
- Increase readability and information density
> Fix table styles in vaults post

- src/lib/components/SummaryBox.svelte
- src/lib/components/css/color.css
- src/lib/trade-executor/schemas/chart.ts
- src/routes/strategies/[strategy]/tech-details/+error.svelte
- src/routes/strategies/[strategy]/tech-details/+layout.svelte
- src/routes/strategies/[strategy]/tech-details/+layout.ts
- src/routes/strategies/[strategy]/tech-details/analysis/+layout.ts
- src/routes/strategies/[strategy]/tech-details/analysis/+page.svelte
- src/routes/strategies/[strategy]/tech-details/analysis/+page.ts
- src/routes/strategies/[strategy]/tech-details/analysis/PairsSelector.svelte
- src/routes/strategies/[strategy]/tech-details/logs/+page.svelte
- src/routes/strategies/[strategy]/tech-details/status/+page.ts
> Add strategy charts (analysis) page

- src/lib/trade-executor/schemas/chart.ts
- src/routes/strategies/[strategy]/tech-details/analysis/+page.svelte
- src/routes/strategies/[strategy]/tech-details/analysis/+page.ts
- src/routes/strategies/[strategy]/tech-details/analysis/PairsSelector.svelte
- Enable single or multi pair selection
- Add search filter
> PairSelector enhancementss
