src/lib/header/Navbar.svelte
src/lib/search/ResultLineItem.svelte
src/lib/search/Search.svelte
src/lib/search/trading-entities.ts
src/routes/search.svelte
src/routes/search/_FacetFilter.svelte
src/routes/search/_Filter.svelte
src/routes/search/_RangeFilter.svelte
src/routes/search/_ResultLineItem.svelte
src/routes/search/_SortSelect.svelte
src/routes/search/index.svelte

This PR builds on top of #11 with an advanced search page:
* provides a variety of filter and sort options
* displays additional data for each row (price, liquidity, volume)
* shows up to 200 matching results
This PR depends on #11, which depends on #13.
I believe this is in good shape to merge. Let me know if you have any questions or feedback on code / user experience.
* hide nav search bar on search page
* pass nav-based search query into advanced search
* search page layout (responsive)
* facet-based filters (type, blockchain, exchange)
* numeric range-based filters (volume, liquidity, price change %)
* sort-by options
* clear search options control(s)
* show up to 200 results

Advanced Search UI

---

src/lib/datatable/datatable.svelte

Remove this annoying horizontal scroll for good:

Remove the horizontal scroll showing in datatable sometimes

---

src/routes/search/index.svelte

Taking @miohtama's suggestion – toggle label between "Select Filters" / "× Clear Filters" and improved styling.
resolves #19

Improve clear filters UI

---

src/routes/search/_FacetFilter.svelte
src/routes/search/_NumericFilter.svelte
src/routes/search/_RangeFilter.svelte
src/routes/search/index.svelte

Modified the breakpoints per the issue (5%).
I went with shorter labels so they don't wrap at lower breakpoints. Also… I wasn't sure if you wanted to keep the "neutral" option. Current state:
Let me know if you prefer the longer labels (will wrap at some screen widths) and/or if you want to drop "neutral".
fixes #18

Tweak price change filter labels

---

package-lock.json
package.json
svelte.config.js

The `service-worker.js` issue #36 was due to a bug in SvelteKit.
This was fixed in `1.0.0-next.213`; we are currently on `1.0.0-next.210`
https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next213
This is a very low-risk upgrade – just 3 patch versions with no flagged _breaking_ changes.
I ran the cypress suite and did some additional manual testing – everything looks 👌 
reverts #37 / preferable solution to fix #36

upgrade SvelteKit to 1.0.0-next.213

---

cypress/integration/home.spec.js
src/lib/helpers/googleMeta.ts
src/routes/index.svelte

Added Google [Sitelinks search box](https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox) metadata to home page.
I tested this using `nginx` and Google's [Rich Results Test](https://search.google.com/test/rich-results) utility – the metadata appears to be recognized correctly.
Added a Cypress test.
closes #29

implement Google SiteLinks search box

---

src/lib/search/TradingEntityHit.svelte

fixes #64
Hiding the price change % value when `price_change_24h` is not present in the search result line item (i.e., this value is not set in Typesense index / not available).
Note that tokens have a value of `0` for `price_usd_latest` (in Typesense) so a price value of `$0` is still displayed. If this is _not_ the desired behavior, I think we should fix this by setting `price_usd_latest` to `null` rather than special-casing this in the UI code.

Fix NaN% price change in advanced search results

---

src/routes/search/_FacetFilter.svelte

update ts import syntax – fixes error on `/search` page in dev (apparently introduced with recent lib upgrades)

fix dev-specific typescript import error

---

package-lock.json
package.json
src/lib/header/PageLoadProgressBar.svelte
src/routes/slow-load.svelte

- use navigating store instead of outdated nav events
- use html5 semantic <progress> element
- use svelte-fsm for deterministic state management
- improve /slow-load test page
fixes #87

Fix page load progress bar

---

src/lib/chart/ChartIQ.svelte
src/lib/chart/ChartLinker.ts
src/lib/chart/quoteFeed.ts
src/routes/trading-view/[chain]/[exchange]/[pair]/_ChartSection.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/index.svelte

- tell ChartIQ to cleanup gaps
- use pair's first trade date to determine when no more data available
- prevent infinite request loops (abort duplicate requests)
- limit max ticks requested to 2000
fixes #96

fix issues with ChartIQ quote feed

---

server.js
src/routes/invalid/[...path].svelte

Wrapper service to handle malformed URIs.
Run this locally:
```bash
SSR=true npm run build
node server.js
```
then try testing
http://localhost:3000/%CD%EA%D5%FB.rar
We've had other exceptions cause fatal errors on the `node` service (e.g., `fetch` DNS errors). We can't anticipate ahead-of-time all the unhandled exceptions that cause `node-adapter` to explode. Recommendation: wrap the `node` command in a simple supervisor to restart on exit, such as:
```bash
while true; do
node server.js
sleep 1
done
```
We could add some error output to this so it's easier to track down in the logs.
I still need to submit a GH issue to the SvelteKit project (will do so Thursday).
fixes #102

add node-adapter wrapper for malformed URIs

---

package-lock.json
package.json

Upgrade to `8.7.0` does not cause any issues. Tested locally, including with a UTC+ timezone 🙃.
**NOTE:** this needs to be merged and deployed before 08.07.2022 (our old `v8.6.0-dev` license expires on that date).
Test locally with:
```shell
TS_PUBLIC_FRONTEND_VERSION_TAG=pr-135 docker-compose up -d
```
closes #131

upgrade chartiq from 8.6.0-dev to 8.7.0

---

src/lib/chart/ChartIQ.svelte
src/lib/chart/quoteFeed.ts
src/lib/chart/timeBucketConverters.ts

It appears this defect was introduced with PR #97 (fix for #96).
Using timezone-aware dates in ChartIQ (necessary so the browser doesn't lock up in UTC+ timezones) causes the "hour" `timeUnit` to no longer work. For `4h` ticks, ChartIQ requires a "minute" `timeUnit` with `interval=60` and `period=4`. See: [ChartIQ setPeriodicity](https://documentation.chartiq.com/CIQ.ChartEngine.html#setPeriodicity).
However… using the above periodicity causes the x-axis floating label to display incorrectly (off by 2h). I believe this is a ChartIQ bug – will open an issue with them. For now, I added a one-line fix to adjust the time in the floating label.
I've tested this across with all time-bucket options across a variety of trading pairs. Everything seems to work correctly. I also tested with my …

fix 4h candles chart rendering bug

---

src/lib/components/Button.svelte
src/lib/components/Header.svelte
src/lib/search/Search.svelte
src/lib/search/Search.test.ts
src/lib/search/TradingEntityHit.svelte

closes tradingstrategy-ai/design-system#87
@allozaur the figma design depends on various global Theme 0.2 updates which have not been implemented yet. To keep the code DRY / continue using existing components, I took some minor liberties with the design to back-port the search layout changes into the Theme 0.1 style. The result is somewhat of a hybrid but I think it works for now.
As we find time to prioritized Theme 0.2 updates across the site, the "final" version will match your figma designs much more closely.
Let me know if you have any tweaks to this intermediate / hybrid version in the meantime.

Top-nav search button discoverability

---

src/routes/strategy/[strategy_id]/logs/LogMessageList.svelte

Logs are not readable on non-retina screens.
Update with 
- Bolder font
- Better colours
- Adjust line height and font size to increase information density
- Further dim the separator line

Improve log readability

---

src/routes/strategy/[strategy_id]/decision-making/+page.svelte
src/routes/strategy/[strategy_id]/decision-making/+page.ts
src/routes/strategy/[strategy_id]/source/+page.svelte
src/routes/strategy/[strategy_id]/source/+page.ts
src/routes/strategy/[strategy_id]/source/SourceCode.svelte

- Add /source page under strategy
- Add /decision making page under strategy
`trade-executor-frontend` navigation has been already updated here:
https://github.com/tradingstrategy-ai/trade-executor-frontend/commit/6251c2d808ea1f6491460dae4282c1b24eb74235

Source and decision making strategy pages

---

vite.config.js

Vite no longer creates a vendor chunk, so you don't need to do this as it will have no effect

remove outdated vite config

---

README.md

the note in the sapper documentation doesn't apply to sveltekit at all. `vite-plugin-svelte` will bundle any package it determines to be a Svelte library (i.e. ones that have `svelte` as a dependency or peer dependency)

update outdated reference to sapper documentation

---

package-lock.json
package.json
src/lib/components/PageHeader.svelte
src/lib/helpers/formatters.ts
src/lib/search/Search.svelte
src/lib/search/TradingEntityHit.svelte
src/routes/search/SortSelect.svelte
src/routes/search/SortSelect.test.ts
src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte

closes #197 
**Screenshot from top-nav "quick search":**
**Screenshot from advanced search:**
> **NOTE:** the Uniswap v2 pairs are flagged as low-quality due to their low liquidity; the liquidity is ignored for the Uniswap v3 pairs

Uniswap v3 search improvements

---

src/routes/trading-view/[chain]/[exchange]/export-data/+page.svelte

- Wrong labels were used for sorting options, causing a backend crash
- Added a warning about the beta quality
- Prod users to full datasets more aggressively
- There is a test error, but not sure if it is related

Fix Microsoft Excel export of top trading pairs.

---

src/lib/helpers/formatters.ts
src/lib/search/TradingEntityHit.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoSummary.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/TimePeriodSummaryColumn.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/TimePeriodSummaryTable.svelte

close #314, #315, #316, #321
**NOTE:** The `pair` attribute `pool_swap_fee` has been renamed to `pair_swap_fee` in `backend`. It should be renamed in `frontend` as well… but it needs to be updated in the Typesense `search` index first.
See:
- tradingstrategy-ai/search#14
- tradingstrategy-ai/frontend#327

Misc pair details fixes

---

docker-compose.yml
docs/docker.md
docs/monitoring.md
package-lock.json
package.json

closes #95
This PR adds basic Datadog tracing for the `frontend` service. This is a first steps towards addressing #128.
As a next step, we could add [StatsD metrics collection](https://docs.datadoghq.com/integrations/node/). We could then instrument the code to capture metrics for `fetch()` requests.
This PR includes a new `docker-compose.yml`. This file should be copied to the production `/frontend` directory when deploying (before running `update-production.sh`).

add Datadog tracing library

---

src/routes/glossary/api/glossary.ts

Add a better error handling so that the page won't open if there is problem with glossary HTML source data.

Hotfixes for the glossary section

---

docker-compose.yml
package-lock.json
package.json
src/app.d.ts
src/hooks.server.ts
src/lib/config.ts
src/routes/+error.svelte
src/routes/sentry-test/+page.svelte

closes #406
I have tested this locally (with `dev` server and with `docker-compose`). It works when I use a DSN from trial instance of Sentry that I created. But when I switch to the `sentry.tradingstrategy.ai` DSN, I don't see any errors coming though.
@hieuh25 or @sontn1988 – any thoughts?

add Sentry error logging for node server

---

src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte

- adds button to allow user to copy python specific information regarding the trading pair
- Perhaps we should also have some sort of indication (tooltip) that code has been copied e.g. Github shows a `Copied` tooltip when copying a codeblock?
- Fixes #420

add button to copy python identifier

---

src/lib/components/TradingDataInfo.svelte
src/routes/glossary/+page.svelte
src/routes/trading-view/[chain]/tokens/[token]/+page.svelte

Close #434
I handled these issues:
Now the glossary entries spacing is better balanced for Desktop/Mobile usage.
Issue was that a super long name was overlaying other UI. I handled this with truncation.

GSC Mobile Usability fixes

---

src/lib/helpers/formatters.ts
src/lib/helpers/trade.ts
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/+page.svelte
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/TradeTable.svelte
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/trade-[trade]/+page.svelte

- Adds buy and sell price databoxes to the position summary 
- Also adds price databox to trade level summary
- Logic may change when shorting is implemented
- In the future, may require some redesigning
- Fixes https://github.com/tradingstrategy-ai/frontend/issues/472

add buy+sell prices

---

src/routes/strategies/ChartThumbnail.svelte

- Adjust strategy tile charts so that small moves are dampened not looking irrational (always max scale)
-

Adjust strategy tile charts 

---

src/lib/components/Badge.svelte
src/lib/components/index.ts
src/lib/helpers/formatters.ts
src/routes/strategies/Badge.svelte
src/routes/strategies/KeyMetric.svelte
src/routes/strategies/KeyMetricTooltip.svelte
src/routes/strategies/StrategyTile.svelte

- Rework the tooltip and backtest hint design
- More help links
- Tweak name and values
NOTE: Currently `MATIC-USD breakout on Uniswap v3` is set to special mode that it always displays live data instead of backtest data for the UI testing purposes.

Strategy tile updates II

---

src/routes/strategies/KeyMetric.svelte
src/routes/strategies/StrategyTile.svelte
src/routes/strategies/[strategy]/(nav)/+layout.svelte
src/routes/strategies/[strategy]/(nav)/StrategyNav.svelte
src/routes/strategies/[strategy]/(nav)/backtest/+page.svelte
src/routes/strategies/[strategy]/(nav)/backtest/+page.ts
src/routes/strategies/[strategy]/+layout.svelte

- There is new property ` data?.summary?.backtest_available` which webhook uses to indicate whether a strategy has a generated backtest report available over the webhook
- Add a trade execution page to display backtest results
- Loads a HTML file from the webhook and this displayed in iframe
- Iframe is different domain, so special `postMessage` trick is used to resize it correctly
- Link to backtest page on the strategy tile
- Remove "live" badge on the strategy tile as it feels a bit unnecessary

Backtest results

---

src/lib/components/Tooltip.svelte
src/lib/components/TradingDataInfoRow.svelte
src/lib/explorer/BorrowAprCell.svelte
src/lib/explorer/LendingReserveTable.svelte
src/lib/explorer/lending-reserve-client.ts
src/lib/helpers/formatters.ts
src/lib/helpers/lending-reserve.ts
src/lib/trade-executor/helpers/formatters.ts
src/routes/strategies/KeyMetric.svelte
src/routes/strategies/StrategyTile.svelte
src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/FlagCell.svelte
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position]/+page.svelte
src/routes/trading-view/[chain]/[exchange]/InfoTable.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte
src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.ts
src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/InfoSummary.svelte
src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/InfoTable.svelte
src/routes/trading-view/[chain]/tokens/[token]/InfoTable.svelte

- display borrow rates as "N/A" for non-borrowable reserves (on both index and details page)
- adjust summary text for non-borrowable tokens
- add tooltips to lending reserve info table
close #539

Display non-borrowable reserves correctly

---

src/lib/components/Tabs.svelte
src/routes/strategies/[strategy]/(nav)/logs/+page.svelte
src/routes/strategies/[strategy]/(nav)/logs/LogEntriesList.svelte

fix #572
- show strategy executor log entries >= log level
- fix log entry order/scroll position bug

Fix strategy log filter (>= level number)

---

src/lib/wallet/ConnectWallet.svelte
src/lib/wallet/client.ts
src/routes/wizard/deposit/payment/+page.svelte
src/routes/wizard/redeem/shares-redemption/+page.svelte

Improve investor wizard error messaging

---

src/lib/chart/HudRow.svelte
src/lib/chart/PairCandleChart.svelte
src/lib/chart/ReserveInterestChart.svelte
src/lib/chart/chart.css

Close tradingstrategy-ai/design-system#139

Lending Reserve Chart UI improvements

---

package-lock.json
package.json
src/routes/wizard/connect-wallet/success/+page.svelte
src/routes/wizard/deposit/balance/+page.svelte
src/routes/wizard/deposit/introduction/+page.svelte
src/routes/wizard/deposit/payment/+page.svelte
src/routes/wizard/deposit/success/+page.svelte
src/routes/wizard/redeem/deposit-status/+page.svelte
src/routes/wizard/redeem/shares-redemption/+page.svelte

close #621
- upgrade wagmi, viem and aave libs
- improve txn failed error messages
- improve wizard copy (replace 'invest' with alt terms)
- log handled wizard errors to Sentry

Improve blockchain transaction processing feedback

---

src/lib/components/DataBadge.svelte
src/lib/explorer/TradingDescription.svelte
src/routes/strategies/+page.svelte
src/routes/strategies/StrategyBadges.svelte
src/routes/strategies/StrategyTile.svelte
src/routes/strategies/StrategyTile.test.ts
src/routes/strategies/[strategy]/(nav)/+layout.svelte
src/routes/strategies/[strategy]/(nav)/[status=positionStatus]-positions/PositionFlag.svelte
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/+page.svelte
src/routes/strategies/[strategy]/[status=positionStatus]-positions/[position=integer]/trade-[trade=integer]/+page.svelte
tests/integration/strategies/index.test.ts

towards #649
Add badges (based on `strategy.tags`) to strategy tiles and page heading.

Add "Beta" badge to strategies (universal)

---

package-lock.json
package.json

update to v9.0.0-key2 with new key.js file

update ChartIQ license key

---

src/routes/trading-view/[chain]/[exchange]/[pair]/+page.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoSummary.svelte
src/routes/trading-view/[chain]/[exchange]/[pair]/InfoTable.svelte
src/routes/trading-view/[chain]/lending/[protocol]/[reserve]/+page.svelte

close #642
- include swap fee in heading for all trading pairs
- *add blockchain logo to pair details subtitle
- update pair details page InfoTable
- remove Uniswap v3 beta warning from pair details
- replace buy/sell buttons with heading swap button
- remove "Blockchain explorer" button (redundant)
- move pair details secondary buttons into info summary

Pair details refresh (part 1)

---

src/lib/components/AlertItem.svelte
src/lib/trade-executor/components/StrategyIcon.svelte
src/lib/trade-executor/strategy/configuration.ts
src/lib/wallet/MyDeposits.svelte
src/routes/+page.server.ts
src/routes/strategies/StrategyTile.svelte
src/routes/strategies/[strategy]/+layout.svelte
src/routes/trading-view/[chain=slug]/[exchange]/[pair]/+page.svelte

close #798
- add config option
- add "outdated" warning to overview page
- disable "Deposit" button on outdated strategies
- add "Outdated" badge to outdated strategies
- exclude outdated strategies from front page

Add support for deprecated/outdated strategies

---

src/lib/components/Tooltip.svelte
src/lib/trade-executor/components/KeyMetric.svelte
src/lib/trade-executor/components/KeyMetricDescription.svelte
src/lib/trade-executor/components/StrategyIcon.svelte
src/routes/FeaturedStrategies.svelte
src/routes/strategies/ChartThumbnail.svelte
src/routes/strategies/StrategyDataSummary.svelte
src/routes/strategies/StrategyTile.svelte

close #803
- replace strategy tile token icons with chain icon
- remove badges
- hide some metrics
- simplify "outdated" strategy icon
- improve tooltip styling

Simplified strategy tile on front page

---

src/lib/trade-executor/state/position-info.test.ts
src/lib/trade-executor/state/position-info.ts
src/routes/strategies/[strategy]/[status=positionStatus]-positions/PositionTable.svelte

close #808
- treat unfrozen positions as "stillOpen"
- use correct value property for open positions

Fix unfrozen open position bug

---

src/lib/newsletter/OptInBanner.svelte
src/routes/glossary/[slug=slug]/+page.svelte

close #830
- update newsletter opt-in banner copy
- remove "additional info" tiles from glossary details page

Update newsletter opt-in banner

---

src/routes/strategies/[strategy]/+layout.svelte
src/routes/strategies/[strategy]/+layout.ts

close #851
- prevent non-admins from viewing private strategies
- display "don't shware" notice on private strategy pages

Prevent sharing of private strategies

---

src/lib/trade-executor/vaults/base.ts
src/lib/trade-executor/vaults/enzyme/index.ts
src/lib/trade-executor/vaults/hot_wallet/index.ts
src/lib/trade-executor/vaults/index.ts
src/lib/trade-executor/vaults/lagoon/index.ts
src/lib/trade-executor/vaults/velvet/index.ts
src/routes/strategies/StrategyDataSummary.svelte
src/routes/strategies/[strategy]/+layout.ts
src/routes/strategies/[strategy]/StrategyNav.svelte
src/routes/strategies/[strategy]/fees/+page.svelte
src/routes/strategies/[strategy]/fees/+page.ts

close #889
toward #868
- modify /fees page to get fees from vault adapter
- add Lagoon protocol fee and tooltip/link
- get Lagoon vault fees from vault smart contract
- add Velvet Capital protocol fee and tooltip/link

Fetch Lagoon vault fees from smart contract

---

src/lib/charts/Series.svelte
src/lib/charts/candle-data-feed.svelte.ts

- use endDate field to determine next fetch endDate
- fetch consistent number of ticks (seems to reduce TV error)

tv-chart: improve DataFeed fetch logic

---

src/lib/charts/ChartTooltip.svelte
src/lib/charts/PairCandleChart.svelte
src/lib/charts/TvChart.svelte
src/routes/strategies/[strategy]/StrategyPerformanceChart.svelte

tv-chart: use color-mix instead of relative color syntax

---

src/routes/strategies/[strategy]/period-performance/+server.ts
src/routes/strategies/[strategy]/snapshot/+page.ts
src/routes/strategies/[strategy]/snapshot/+page@.svelte

- Use share price data on period-performance endpoint and performance snapshot page
- Don't resample data when calculating period performance or rendering performance snapshot chart
- Use last entry prior to requested end date for period performance periods
close #971 
close #972

More share price updates
